add_newline = true

[directory]
truncation_length = 1
truncate_to_repo = false
disabled = false
style = 'bold blue'
fish_style_pwd_dir_length = 3

[git_branch]
symbol = " "
disabled = false

[git_status]
disabled = false
style = 'bold red'
conflicted = '[=](bold red)'
ahead = '[⇡${count}](bold purple)'
behind = '[⇣${count}](bold purple)'
diverged = '[⇕⇡${ahead_count}⇣${behind_count}](bold purple)'
untracked = '[?${count}](bold yellow)'
stashed = '[!${count}](bold cyan)'
modified = '[ ${count}](bold red)'
staged = '[${count}](bold blue)'
renamed = '[»${count}](bold red)'
deleted = '[✘${count}](bold red)'

[cmd_duration]
disabled = false

[nodejs]
disabled = true

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'
vicmd_symbol = '[<](bold green)'

[shell]
disabled = false
format = '$indicator'
fish_indicator = ''
zsh_indicator = '[\[zsh\]](bold #4b5263)'
bash_indicator = '[\[bsh\]](bold #4b5263)'
