add_newline = false

[directory]
disabled = false
style = 'bold blue'

[git_branch]
disabled = false

[git_status]
disabled = false
style = 'bold red'
conflicted = '[=](bold red)'
ahead = '[⇡${count}](bold purple)'
behind = '[⇣${count}](bold purple)'
diverged = '[⇕⇡${ahead_count}⇣${behind_count}](bold purple)'
untracked = '[?${count}](bold yellow)'
stashed = '[!${count}](bold cyan)'
modified = '[${count}](bold red)'
staged = '[${count}](bold blue)'
renamed = '[»${count}](bold red)'
deleted = '[✘${count}](bold red)'

[cmd_duration]
disabled = false

[nodejs]
disabled = true

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'
vicmd_symbol = '[<](bold green)'

[shell]
disabled = false
format = '$indicator'
fish_indicator = ''
zsh_indicator = '[\[zsh\]](bold red)'
bash_indicator = '[\[bsh\]](bold red)'
