#!/usr/bin/guile
-s
!#
;; Add the current path to the guile load path
(add-to-load-path (dirname (current-filename)))

;; Load the river module
(use-modules (river)
             (variables)
             (srfi srfi-60))

(river
 #:startup-commands
 `(("dbus-update-activation-environment"
    "DISPLAY"
    "WAYLAND_DISPLAY"
    "XDG_SESSION_TYPE"
    "XDG_CURRENT_DESKTOP")
   "kanshi"
   "waybar"
   "dunst"
   "swaybg -i ~/pictures/wallpaper.jpg"
   ("rm" "-f" ,wob-socket "&&"
    "mkfifo" ,wob-socket "&&"
    "tail" "-f" ,wob-socket "|" "wob")
   ("wl-paste" "-t" "text" "--watch" "clipman" "store" "--max-items" 1024)
   ("swayidle" "-w"
    "timeout" 180 "'",lockscreen "'"
    "timeout" 300 "'wlopm --off \\*'" "resume" "'wlopm  --on \\*'"
    "before-sleep" "'playerctl pause'"
    "before-sleep" "'" ,lockscreen "'"))
 #:inputs
 '((keyboard-layout . ((-variant altgr-intl us)))
   ((input . "pointer-2-7-SynPS/2_Synaptics_TouchPad") .
    ((events ."disabled-on-external-mouse")
     (drag . #t)
     (disable-while-typing . #t)
     (natural-scroll . #t)
     (scroll-method . "two-finger"))))
 #:options
 '((attach-mode . "bottom")
   (background-color . "0x2e3440")
   (border-color-focused . "0x81a1c1")
   (border-color-unfocused . "0x2e3440")
   (border-color-urgent . "0xbf616a")
   (border-width . 3)
   (set-repeat . (50 . 300))
   (focus-follows-cursor . #f)
   (hide-cursor . (timeout . 5000))
   (hide-cursor . (when-typing . #t))
   (set-cursor-warp . "on-output-change")
   (xcursor-theme . ("Breeze_Snow" . 24))
   (default-layout . rivertile))
 #:keymaps
 `((("normal") . ,(append
                   `(;;River
                     (Mod4 Escape (spawn ,lockscreen))
                     (Mod4+Shift Q (exit))
                     ;; Launch applications
                     (Mod4 Return (spawn ,term))
                     (Mod4+Shift Return (spawn  ,launcher))
                     (Mod4 B (spawn ,browser))
                     (Mod4+Shift Y (spawn clipman pick -t rofi))
                     (Mod4 O (enter-mode open))
                     ;; Window management
                     (Mod4 D close)
                     (Mod4 K (focus-view next))
                     (Mod4 J (focus-view previous))
                     (Mod4+Shift K (swap next))
                     (Mod4+Shift J (swap previous))
                     (Mod4 M zoom)
                     (Mod4+Shift M toggle-fullscreen)
                     (Mod4 F toggle-float)
                     (Mod4 P (focus-output previous))
                     (Mod4 N (focus-output next))
                     (Mod4+Shift P (send-to-output previous))
                     (Mod4+Shift N (send-to-output next))
                     (Mod4 H (send-layout-cmd rivertile "'main-ratio -0.01'"))
                     (Mod4 L (send-layout-cmd rivertile "'main-ratio +0.01'")))
                   ;; Layout management
                   ;; Tag management
                   (map
                    (lambda (tag)
                      `(Mod4 ,(+ tag 1) (set-focused-tags
                                         ,(arithmetic-shift 1 tag))))
                    (iota 6))
                   (map
                    (lambda (tag)
                      `(Mod4+Shift ,(+ tag 1) (set-view-tags
                                               ,(arithmetic-shift 1 tag))))
                    (iota 6))
                   (map
                    (lambda (tag)
                      `(Mod4+Control ,(+ tag 1) (toggle-focused-tags
                                                 ,(arithmetic-shift 1 tag))))
                    (iota 6))))
   (("normal" "locked") . (;;Special keys
                           (repeat None XF86AudioRaiseVolume (spawn ,volume-up))
                           (repeat None XF86AudioLowerVolume (spawn ,volume-down))
                           (None XF86AudioMute (spawn ,volume-mute))
                           (None XF86AudioMicMute (spawn ,volume-mic-mute))
                           (None XF86AudioPlay (spawn ,audio-play))
                           (None XF86AudioNext (spawn ,audio-next))
                           (None XF86AudioPrev (spawn ,audio-prev))
                           (None XF86AudioStop (spawn ,audio-stop))
                           (repeat None XF86MonBrightnessUp (spawn ,brightness-up))
                           (repeat None XF86MonBrightnessDown (spawn ,brightness-down))))
   (("open") . (;; Open misc applications
                (None B (spawn riverctl enter-mode normal "&&" ,bib))
                (None P (spawn riverctl enter-mode normal "&&" ,pass))
                (None S (spawn riverctl enter-mode normal "&&" ,screenshot-area))
                (Shift S (spawn riverctl enter-mode normal "&&" ,screenshot-full))
                (None Escape (enter-mode normal)))))
 #:mousemaps
 '((("normal") . ((Mod4 BTN_LEFT move-view)
                  (Mod4 BTN_RIGHT resize-view))))
 #:window-rules
 '(("float-filter" .
    ((app-id . (float
                popup
                pavucontrol
                origin
                nm-connection-editor))
     (title . ("Picture in Picture"
               Picture-in-Picture
               "Save File"))))
   ("csd-filter" .
    ((app-id . ("\\*")))))
 #:gsettings
 '(("org.gnome.desktop.interface" .
    ((gtk-theme . "Nordic")
     (icon-theme . "Papirus-Dark")
     (cursor-theme . "Breeze_Snow")
     (cursor-size . 24)))
   ("org.gnome.desktop.wm.preferences" .
    ((button-layout . ""))))
 #:layout-generator
 '("rivertile" . ((-view-padding . 3)
                  (-outer-padding . 3)
                  (-main-location . "left")
                  (-main-count . 1)
                  (-main-ratio . 0.5))))
