# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

right_format = "$cmd_duration"

[c]
symbol = "󰙱"

[character]
disabled = true
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold green)"
vimcmd_replace_one_symbol = "[<](bold green)"
vimcmd_replace_symbol = "[<](bold purple)"
vimcmd_visual_symbol = "[<](bold blue)"

[cmd_duration]
disabled = false

[directory]
truncation_length = 1
truncate_to_repo = false
read_only = "󰌾 "
disabled = false
style = "bold blue"
fish_style_pwd_dir_length = 3

[docker_context]
symbol = " "

[git_branch]
symbol = "󰘬 "
disabled = false

[git_status]
disabled = false
format='([\[ $all_status$ahead_behind\]]($style) )'
style = "bold red"
conflicted = "[  ](bold red)"
ahead = "[${count} ](bold purple)"
behind = "[${count} ](bold purple)"
diverged = "[${ahead_count}${behind_count} ](bold purple)"
untracked = "[ ${count} ](bold yellow)"
stashed = "[ ${count} ](bold cyan)"
modified = "[ ${count} ](bold red)"
staged = "[ ${count} ](bold blue)"
renamed = "[ ${count} ](bold red)"
deleted = "[ ${count} ](bold red)"

[golang]
symbol = "󰟓 "

[guix_shell]
symbol = " "

[haskell]
symbol = "󰲒 "

[java]
symbol = "󰬷 "

[julia]
symbol = " "

[lua]
symbol = "󰢱 "

[memory_usage]
symbol = "󰍛 "

[nix_shell]
symbol = "󱄅 "

[nodejs]
symbol = "󰎙 "

[package]
symbol = "󰏗 "

[python]
symbol = "󰌠 "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = "󰴭 "

[rust]
symbol = "󱘗 "

[shell]
disabled = false
format = "[$indicator]($style)"
style = "bold #3e4451"
bash_indicator = '\[bsh\]'
fish_indicator = '\[fsh\]'
zsh_indicator = '\[zsh\]'
powershell_indicator = '\[pwsh\]'
ion_indicator = '\[ion\]'
elvish_indicator = '\[esh\]'
tcsh_indicator = '\[tcsh\]'
xonsh_indicator = '\[xonsh\]'
cmd_indicator = '\[cmd\]'
nu_indicator =  '​'
unknown_indicator = '\[?\]'
